### ISSUE TITLE
Just updated to 0.3.0

### ISSUE THREAD

**Issue by albertbuchard** [aki77/atom-expand-region#22]
Failed to load the expand-region package
Unexpected token o in JSON at position 5224 in /Users/Pro/.atom/packages/expand-region/package.json
Hide Stack Trace
SyntaxError: Unexpected token o in JSON at position 5224
    at Object.parse (native)
    at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:54:19)
    at parseContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:68:16)
    at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:170:14)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:721:29)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:407:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28
  at /Users/Pro/.atom/packages/expand-region/package.json:1:1

**Comment by aki77** [comment]
When Atom v1.16.0 on OSX, I can't reproduce this issue..
Please try reinstall the package.

```
$ apm uninstall expand-region
$ apm install expand-region
```
